<?
include_once("../setting.inc.php");
$a = array();
if ($_GET["html5"])
{
  header("Content-Type: application/json; charset=utf-8");
  
  $def = get_setting("beamer_current_playlist");
  if ($def)
  {
    die( file_get_contents($def) );
  }
  
  $out = new stdClass();
  $out->name = "autoGeneratedSlideList";
  $out->creationTime = date("Y-m-d H:i:s");
  $out->settings = new stdClass();
  $out->settings->autoRotate = true;

  $a = glob("*");
  foreach ($a as $v) 
  {
    if($v == ".") continue;
    if($v == "..") continue;
    if($v == "index.php") continue;
    $url = $dir . "/" . $v;
    //printf("\t<slide lastChanged='%d'>%s</slide>\n",filemtime($v),$url);
    $o = new stdClass();
    $ext = strtolower(substr($v,strrpos($v,".")+1));
    switch($ext)
    {
      case "gif":
      case "jpeg":
      case "jpg":
      case "png":
        {
          $o->type = "image";
          $o->filename = "../slides/".$v;
          $o->lastModified = filemtime($v);
          $out->slides[$o->filename] = $o;
        } break;
      case "m4v":
      case "ogv":
      case "mpg":
      case "mp4":
        {
          $o->type = "video";
          $o->filename = "../slides/".$v;
          $o->lastModified = filemtime($v);
          $out->slides[$o->filename] = $o;
        } break;
      case "txt":
        {
          $o->type = "text";
          $o->contents = file_get_contents($v);
          $o->filename = "../slides/".$v;
          $o->lastModified = filemtime($v);
          $out->slides[$o->filename] = $o;
        } break;
      case "htm":
      case "html":
        {
          $o->type = "html";
          $o->contents = file_get_contents($v);
          $o->filename = "../slides/".$v;
          $o->lastModified = filemtime($v);
          $out->slides[$o->filename] = $o;
        } break;
    }
  }
  
  echo json_encode($out,JSON_PRETTY_PRINT);
}
else
{
  $a = array_merge($a,glob("*.{j,J}{p,P}{g,G}",GLOB_BRACE));
  $a = array_merge($a,glob("*.{p,P}{n,N}{g,G}",GLOB_BRACE));

  header("Content-Type: text/xml; charset=utf-8");
  echo "<".'?xml version="1.0" encoding="UTF-8" ?'.">";
  
  list($path) = explode("?",$_SERVER["REQUEST_URI"]);
  $dir = ($_SERVER["HTTPS"]=="on"?"https":"http") . "://" . $_SERVER["SERVER_NAME"] . dirname($path . "/dummy.txt");
  if ($_GET["allSlides"])
    $dir = "../slides";
    
  echo "<slides>\n";
  foreach ($a as $v) {
    if($v == ".") continue;
    if($v == "..") continue;
    if($v == "index.php") continue;
    $url = $dir . "/" . $v;
    printf("\t<slide lastChanged='%d'>%s</slide>\n",filemtime($v),$url);
  }
  echo "</slides>\n";
}
?>